#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from os import devnull
import sys
import os
import re
from types import TracebackType
from multilanguage import *


class AutoGen:
    OR_info = []
    EC_path = []
    verbose = False
    debug = False

    def __init__(self) -> None:
        self.parse_args()
        self.clean_out()
        self.find_EC_path()
        self.find_EC_content()
        self.find_OperationRegion()
        self.find_field()

    def show_help(self):
        print(HELP_MESSAGE)

    def parse_args(self):
        arg_lens = len(sys.argv)
        if arg_lens == 1:
            self.show_help()
            exit()
        for arg in sys.argv:
            if '-h' in arg or 'help' in arg:
                self.show_help()
                exit()
            if '-v' in arg:
                self.verbose = True
            if '-debug' in arg:
                self.verbose = True
                self.debug = True
            if '.dsl' in arg:
                self.filename = arg
                self.filepath = os.path.abspath(arg)
                try:
                    with open(self.filename, 'r') as f:
                        self.file_content = f.read()
                except FileNotFoundError:
                    print(FILE_NOT_FOUND_MSG)
                    exit(1)
                except PermissionError:
                    print(PERMISSION_MSG)
                    exit(1)

    def clean_out(self):
        '''
        Removes comments, external, Firmware error generated by iasl, etc
        '''
        # \w\W 跨行匹配，去除段注释
        self.file_content = re.sub(
            r'/\*[\w\W\n]*?\*/', "", self.file_content)
        # 去除行注释
        self.file_content = re.sub(r'//.*\n', '', self.file_content)
        # 去除 External 声明
        self.file_content = re.sub(r'External.*\n', "", self.file_content)
        # 去除 Firmware Error 说明
        self.file_content = re.sub(
            r'Firmware Error.*\n', "", self.file_content)
        # 去除空行
        self.file_content = re.sub(r'^\n', "", self.file_content)

    def get_content(self, target):
        '''
        Getting file content about given target.

        @param: target(str) - which device/field/method are you finding

        @return: str - file content about that device/field/method
        '''
        if self.debug:
            print('\n\n')
            print("---------------------get content-----------------------")
        dsdt_splited = self.file_content.split(' ')
        stack = []
        trigger = False
        content = ''
        for i in range(0, len(dsdt_splited)):
            word = dsdt_splited[i]
            if dsdt_splited[i] == "DefinitionBlock":
                stack.append("DefinitionBlock")
            elif dsdt_splited[i] == "Field":
                try:
                    name = re.findall(r'\((.*),', dsdt_splited[i+1])[0]
                    trigger = True
                except IndexError:
                    continue
                stack.append(("Field", name))
            elif dsdt_splited[i] == "IndexField":
                try:
                    name = re.findall(r'\((.*),', dsdt_splited[i+1])[0]
                    trigger = True
                except IndexError:
                    continue
                stack.append(("IndexField", name))
            elif dsdt_splited[i] == "Scope":
                try:
                    path = re.findall(r'\((.*)\)', dsdt_splited[i+1])[0]
                    trigger = True
                except IndexError:
                    continue
                stack.append(("Scope", path))
                if self.debug:
                    print("Scope", path)
            elif dsdt_splited[i] == "Method":
                try:
                    name = re.findall(r'\((.*),', dsdt_splited[i+1])[0]
                    trigger = True
                except IndexError:
                    continue
                stack.append(("Method", name))
                if self.debug:
                    print("Method", name)
                    if name == "NPTS":
                        print()
            elif dsdt_splited[i] == "Device":
                try:
                    name = re.findall(r'\((.*)\)', dsdt_splited[i+1])[0]
                    trigger = True
                except IndexError:
                    continue
                stack.append(("Device", name))
                if self.debug:
                    print("Device", name)
                    if name == "PEG0":
                        print()
            elif dsdt_splited[i] == "ThermalZone":
                try:
                    name = re.findall(r'\((.*)\)', dsdt_splited[i+1])[0]
                    trigger = True
                except IndexError:
                    continue
                stack.append(("ThermalZone", name))

            elif dsdt_splited[i] in ("If", "(If"):
                stack.append(None)
            elif dsdt_splited[i] == "Else\n":
                stack.append(None)
            elif dsdt_splited[i] == "ElseIf":
                stack.append(None)
            elif dsdt_splited[i] == "Switch":
                stack.append(None)
            elif dsdt_splited[i] == "Case":
                stack.append(None)
            elif dsdt_splited[i] == "Default\n":
                stack.append(None)
            elif dsdt_splited[i] == "While":
                stack.append(None)
            elif dsdt_splited[i] in ("Buffer", "(Buffer"):
                stack.append(None)
            elif dsdt_splited[i] in ("Package", "(Package"):
                stack.append(None)
            elif dsdt_splited[i] == "IRQ":
                stack.append(None)
            elif dsdt_splited[i] == "IRQNoFlags":
                stack.append(None)
            elif dsdt_splited[i] in ("ResourceTemplate", "(ResourceTemplate"):
                stack.append(None)
            elif dsdt_splited[i] == "Interrupt":
                stack.append(None)
            elif dsdt_splited[i] == "GpioInt":
                stack.append(None)
            elif dsdt_splited[i] == "GpioIo":
                stack.append(None)
            elif dsdt_splited[i] == "StartDependentFn":
                stack.append(None)
            elif dsdt_splited[i] == "StartDependentFnNoPri":
                stack.append(None)
            elif dsdt_splited[i] == "Processor":
                stack.append(None)
            elif dsdt_splited[i] == "PowerResource":
                stack.append(None)
            elif dsdt_splited[i] in ("DMA", "(DMA"):
                stack.append(None)

            elif "}" in dsdt_splited[i]:
                stack.pop()

            if trigger:
                # 触发检查当前路径
                path = ''
                for item in stack:
                    if item:
                        if item[0] == 'Scope':
                            if item[1].startswith('\\'):
                                path = item[1]
                            else:
                                path = '\\' + item[1]
                        elif item[0] == 'Device':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'Method':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'Field':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'IndexField':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'ThermalZone':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                if path == target:
                    # 匹配查找目标时
                    bracket_stack = []
                    for word in dsdt_splited[i:]:
                        if "{" in word:
                            bracket_stack.append('{')
                        if "}" in word:
                            bracket_stack.pop()
                            if len(bracket_stack) == 0:
                                break
                        content += (word+' ')
                trigger = False
        return content

    def find_EC_path(self):
        '''
        Find all "PNP0C09" device in DSDT and return its path as a list.

        @return: list - including all "PNP0C09" device path
        '''
        if self.debug:
            print('\n\n')
            print("---------------------find EC path-----------------------")

        stack = []
        EC_found = False
        dsdt_splited = self.file_content.split()
        # for i in range(0, 5000):
        #    print(dsdt_splited[i])
        for i in range(0, len(dsdt_splited)):
            word = dsdt_splited[i]
            if "PNP0C09" in dsdt_splited[i]:
                EC_found = True
                path = ""
                for item in stack:
                    if item:
                        if item[0] == 'Scope':
                            if item[1].startswith('\\'):
                                path = item[1]
                            else:
                                path = '\\' + item[1]
                        elif item[0] == 'Device':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'Method':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'Field':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'IndexField':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                        elif item[0] == 'ThermalZone':
                            if stack.index(item) != 1:
                                path += '.'
                            else:
                                path = '\\'
                            path += item[1]
                if self.verbose:
                    print("EC Path:", path)
                self.EC_path.append(path)
            elif dsdt_splited[i] == "DefinitionBlock":
                stack.append("DefinitionBlock")
            elif dsdt_splited[i] == "Field":
                try:
                    name = re.findall(r'\((.*),', dsdt_splited[i+1])[0]
                except IndexError:
                    continue
                stack.append(("Field", name))
            elif dsdt_splited[i] == "IndexField":
                try:
                    name = re.findall(r'\((.*),', dsdt_splited[i+1])[0]
                except IndexError:
                    continue
                stack.append(("IndexField", name))
            elif dsdt_splited[i] == "Scope":
                try:
                    path = re.findall(r'\((.*)\)', dsdt_splited[i+1])[0]
                except IndexError:
                    continue
                stack.append(("Scope", path))
                if self.debug:
                    print("Scope", path)
            elif dsdt_splited[i] == "Method":
                try:
                    name = re.findall(r'\((.*),', dsdt_splited[i+1])[0]
                except IndexError:
                    continue
                stack.append(("Method", name))
                if self.debug:
                    print("Method", name)
                    if name == "_CRS":
                        print()
            elif dsdt_splited[i] == "Device":
                try:
                    name = re.findall(r'\((.*)\)', dsdt_splited[i+1])[0]
                except IndexError:
                    continue
                stack.append(("Device", name))
                if self.debug:
                    print("Device", name)
                    if name == "LNKB":
                        print()
            elif dsdt_splited[i] == "ThermalZone":
                try:
                    name = re.findall(r'\((.*)\)', dsdt_splited[i+1])[0]
                except IndexError:
                    continue
                stack.append(("ThermalZone", name))

            elif dsdt_splited[i] in ("If", "(If"):
                stack.append(None)
            elif dsdt_splited[i] == "Else":
                stack.append(None)
            elif dsdt_splited[i] == "ElseIf":
                stack.append(None)
            elif dsdt_splited[i] == "Switch":
                stack.append(None)
            elif dsdt_splited[i] == "Case":
                stack.append(None)
            elif dsdt_splited[i] == "Default":
                stack.append(None)
            elif dsdt_splited[i] == "While":
                stack.append(None)
            elif dsdt_splited[i] in ("Buffer", "(Buffer"):
                stack.append(None)
            elif dsdt_splited[i] in ("Package", "(Package"):
                stack.append(None)
            elif dsdt_splited[i] == "IRQ":
                stack.append(None)
            elif dsdt_splited[i] == "IRQNoFlags":
                stack.append(None)
            elif dsdt_splited[i] in ("ResourceTemplate", "(ResourceTemplate"):
                stack.append(None)
            elif dsdt_splited[i] == "Interrupt":
                stack.append(None)
            elif dsdt_splited[i] == "GpioInt":
                stack.append(None)
            elif dsdt_splited[i] == "GpioIo":
                stack.append(None)
            elif dsdt_splited[i] == "StartDependentFn":
                stack.append(None)
            elif dsdt_splited[i] == "StartDependentFnNoPri":
                stack.append(None)
            elif dsdt_splited[i] == "Processor":
                stack.append(None)
            elif dsdt_splited[i] == "PowerResource":
                stack.append(None)
            elif dsdt_splited[i] in ("DMA", "(DMA"):
                stack.append(None)

            elif "}" in dsdt_splited[i]:
                stack.pop()
        if not EC_found:
            print(EC_NOT_FOUND_MSG)
            exit(1)

    def find_EC_content(self):
        '''
        Find EmbeddedController part content in dsl and return it as a dictionary

        @return: dict - { path : file content }
        '''
        content = {}
        for item in self.EC_path:
            content[item] = self.get_content(item)
        self.EC_content = content

    def find_OperationRegion(self):
        '''
        Find OperationRegion in EC device
        '''
        EC_content = self.EC_content
        for dev in EC_content:
            OR_list = re.findall(
                "OperationRegion \\(([A-Z]{4}),", EC_content[dev])
            for OR in OR_list:
                OR_info = re.search(  # 使用分组来获得 OperationRegion 的信息
                    "OperationRegion \\(%s, ([a-zA-Z].*), ([a-zA-Z0-9].*), ([a-zA-Z0-9].*)\\)" % OR, EC_content[dev])
                try:
                    self.OR_info.append({
                        "Path": dev,
                        "Name": OR,
                        "Storage": OR_info.group(1),
                        "Offset": OR_info.group(2),
                        "Length": OR_info.group(3)
                    })
                except AttributeError:
                    continue
        if self.verbose:
            for item in self.OR_info:
                print(item)
            print()

    def find_field(self):
        for OR_info in self.OR_info:
            content = self.get_content(OR_info["Path"]+'.'+OR_info["Name"])
            print(content)


if __name__ == '__main__':
    app = AutoGen()
